package com.fit2081.nutritrack.data.genAIData

/**
 * AIResponseBody is data class representing the response generated by GenAI.
 * It contains key pattern details to be displayed.
 *
 * Acknowledgement:
 * Full acknowledgment details can be found below.
 */
data class AIResponseBody(

    /**
     * References:
     * The following code lines were taken from the following ed lesson with some modifications.
     *  Lab 7, Part 2b: Coding (Currency Exchange Rate): https://edstem.org/au/courses/20813/lessons/80448/slides/544885
     **/

    val patternName: String,
    val description: String
)
